#!/usr/bin/env python3
"""Generate location_presets_generated.cpp from a private CSV file.

This keeps real location credentials out of Git while still compiling a simple
preset table into the firmware image.

Expected CSV columns:

    id,name,wifi_ssid,wifi_password,mqtt_uri,mqtt_username,mqtt_password

Example:

    home,Home,ExampleSSID,ExamplePassword,mqtt://broker.local:1883,mqtt-user,mqtt-password

Default input:
    factory/location_presets.private.csv

Default output:
    components/location_presets/location_presets_generated.cpp
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT = ROOT / "factory" / "location_presets.private.csv"
DEFAULT_OUTPUT = ROOT / "components" / "location_presets" / "location_presets_generated.cpp"
REQUIRED_COLUMNS = ("id", "name", "wifi_ssid", "wifi_password", "mqtt_uri")
OPTIONAL_COLUMNS = ("mqtt_username", "mqtt_password")
OUTPUT_COLUMNS = REQUIRED_COLUMNS + OPTIONAL_COLUMNS
ID_RE = re.compile(r"^[a-z0-9_]+$")


def cpp_string(value: str) -> str:
    """Return value escaped as a C++ string literal."""
    escaped = []
    for ch in value:
        code = ord(ch)
        if ch == "\\":
            escaped.append("\\\\")
        elif ch == '"':
            escaped.append('\\"')
        elif ch == "\n":
            escaped.append("\\n")
        elif ch == "\r":
            escaped.append("\\r")
        elif ch == "\t":
            escaped.append("\\t")
        elif code < 32 or code == 127:
            escaped.append(f"\\x{code:02x}")
        else:
            escaped.append(ch)
    return '"' + "".join(escaped) + '"'


def read_presets(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        raise FileNotFoundError(f"Input CSV not found: {path}")

    with path.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        if reader.fieldnames is None:
            raise ValueError("CSV is empty")

        missing = [column for column in REQUIRED_COLUMNS if column not in reader.fieldnames]
        if missing:
            raise ValueError(f"CSV is missing required column(s): {', '.join(missing)}")

        presets: list[dict[str, str]] = []
        seen_ids: set[str] = set()
        for line_number, row in enumerate(reader, start=2):
            preset = {column: (row.get(column) or "").strip() for column in OUTPUT_COLUMNS}

            if not any(preset.values()):
                continue

            for column in REQUIRED_COLUMNS:
                if not preset[column]:
                    raise ValueError(f"Line {line_number}: {column} is required")

            if not ID_RE.match(preset["id"]):
                raise ValueError(
                    f"Line {line_number}: id must use lowercase letters, numbers, and underscores only"
                )

            if preset["id"] in seen_ids:
                raise ValueError(f"Line {line_number}: duplicate id {preset['id']!r}")
            seen_ids.add(preset["id"])
            presets.append(preset)

    if not presets:
        raise ValueError("CSV did not contain any presets")

    return presets


def render_cpp(presets: list[dict[str, str]], source_path: Path) -> str:
    rows = []
    for preset in presets:
        rows.append(
            "    {"
            + ", ".join(
                [
                    cpp_string(preset["id"]),
                    cpp_string(preset["name"]),
                    cpp_string(preset["wifi_ssid"]),
                    cpp_string(preset["wifi_password"]),
                    cpp_string(preset["mqtt_uri"]),
                    cpp_string(preset["mqtt_username"]),
                    cpp_string(preset["mqtt_password"]),
                ]
            )
            + "},"
        )

    source_display = source_path.relative_to(ROOT) if source_path.is_relative_to(ROOT) else source_path

    return (
        "// Generated by tools/generate_location_presets.py. Do not edit.\n"
        f"// Source: {source_display}\n\n"
        "#include \"location_presets.h\"\n\n"
        "namespace location_presets {\n\n"
        "namespace {\n\n"
        "const Preset kGeneratedPresets[] = {\n"
        + "\n".join(rows)
        + "\n};\n\n"
        "}  // namespace\n\n"
        "const Preset* generatedPresets(size_t* count)\n"
        "{\n"
        "    if (count != nullptr) {\n"
        "        *count = sizeof(kGeneratedPresets) / sizeof(kGeneratedPresets[0]);\n"
        "    }\n"
        "    return kGeneratedPresets;\n"
        "}\n\n"
        "}  // namespace location_presets\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate location preset C++ source from CSV")
    parser.add_argument(
        "--input",
        type=Path,
        default=DEFAULT_INPUT,
        help=f"private CSV path, default: {DEFAULT_INPUT.relative_to(ROOT)}",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"generated C++ path, default: {DEFAULT_OUTPUT.relative_to(ROOT)}",
    )
    args = parser.parse_args()

    try:
        presets = read_presets(args.input)
        generated = render_cpp(presets, args.input)
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(generated, encoding="utf-8")
    except Exception as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    print(f"Generated {args.output} from {len(presets)} preset(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
